### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by DosMike** [XakepSDK/ViewAPI#1]
I'm setting the scoreboard every second with a synchronous executor.
Since the content is dynamic and changes i clear it and add the lines again.

Every now and then your plugin throws a ConcurrentModificationException:
```
[17:53:56 ERROR] [Sponge]: The Scheduler tried to run the task view-sponge-A-36 owned by Plugin{id=view-sponge, name=View-sponge, version=1.0-SNAPSHOT, descript
ion=Manages sidebars, authors=[Xakep_SDK], source=mods\viewAPI-1.0.jar}, but an error occured.
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_161]
        at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_161]
        at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_161]
        at dk.xakeps.view.impl.SpongeSidebar.updateBuffer(SpongeSidebar.java:142) ~[SpongeSidebar.class:?]
        at dk.xakeps.view.impl.SpongeSidebar.update(SpongeSidebar.java:126) ~[SpongeSidebar.class:?]
        at dk.xakeps.view.impl.SpongeView$Updater.lambda$run$0(SpongeView.java:35) ~[SpongeView$Updater.class:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_161]
        at dk.xakeps.view.impl.SpongeView$Updater.run(SpongeView.java:35) ~[SpongeView$Updater.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-7.1.0-BETA-9]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-7.1.0-BETA-9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

Otherwise great plugin :)

**Comment by XakepSDK** [comment]
If sidebar text isn't static, you should implement `SidebarText` that will provide updated text.
E.g.
Text is `Time left: ${time}`, you should implement something like `TimeText` and this implementation should provide right `Text` for every `getText()` invocation.
Simple example(from bukkit version):
```java
public class OnlineText implements Text {
    private final static Pattern online = Pattern.compile(Pattern.quote("${online}"));
    private final static ServerRegistry data = DataAPI.getServerRegistry();
    private String text;

    public OnlineText(String text) {
        this.text = text;
    }

    @Override
    public String getText() {
        return online.matcher(text).replaceAll(String.valueOf(data.getPlayersCount()));
    }

    @Override
    public void setText(String text) {
        this.text = text;
    }
}
```
This example takes overall players count in all bungee instances and returns text with right players count.

With this plugin you should not write any scheduler to update sidebar's text.

**Comment by DosMike** [comment]
Thats a good idea, but its not only the lines itself that varies, but also the amount of lines i display, so i have to clear and readd at certain points.
I think the error could be prevented 100 % by synchronizing all access to textMap in SpongeSidebar. If you want i can PR that for you

**Comment by XakepSDK** [comment]
Check out new release: https://ore.spongepowered.org/Xakep_SDK/ViewAPI/versions/1.1/download/

**Comment by XakepSDK** [comment]
https://ore.spongepowered.org/Xakep_SDK/ViewAPI/versions/1.2/download

**Comment by XakepSDK** [comment]
If you want to make one-time change, just add listener to sidebar and then set listener to null at the end.
e.g.
```java
sidebar.setUpdateListener(sidebar -> {
    sidebar.clear();
    ...
    sidebar.setUpdateListener(null);
});
```
